require_relative 'hikvision/version'
require_relative 'hikvision/isapi'
require_relative 'hikvision/streaming'
require_relative 'hikvision/streaming/channel'
require_relative 'hikvision/system'
require_relative 'hikvision/system/time'
require_relative 'hikvision/system/device_info'
require_relative 'hikvision/system/reboot'
