require_relative 'hikvision/version'
require_relative 'hikvision/isapi'
require_relative 'hikvision/streaming/streaming'
require_relative 'hikvision/streaming/channel'
require_relative 'hikvision/system/system'
